//
//  Booking.swift
//  CinelliTutoring
//
//  Created by Michael Cinelli on 3/5/25.
//

import Foundation

// This struct represents a tutoring session that a user has booked. 
struct BookingModel: Identifiable, Codable {
    var id: String // unique id for this particular booking // A unique identifier for this booking (usually generated by Firebase)
    var userId: String //userId is fetched from the viewmodel of our MVVM architecture. 
    var startTime: Date
    var endTime: Date
    var status: BookingStatus // The current status of the booking (e.g., pending, confirmed, etc.).
    var amount: Double
    var isPaid: Bool

    // This function converts the data to a dictionary format which is better for FireStore. 
    func toDictionary() -> [String: Any] {
        return [
            "id": id,
            "userId": userId,
            "startTime": startTime,
            "endTime": endTime,
            "status": status.rawValue,
            "amount": amount,
            "isPaid": isPaid
        ]
    }
}

enum BookingStatus: String, Codable {
    case pending
    case confirmed
    case canceled
    case completed
}
