//
//  User.swift
//  CinelliTutoring
//
//  Created by Michael Cinelli on 3/5/25.
//

import Foundation

struct Address: Codable {
    var street: String
    var city: String
    var state: String
    var zipCode: String
}

struct UserModel: Identifiable, Codable {
    var id: String // Random id generated by Firebase
    var firstName: String
    var lastName: String
    var email: String
    var phoneNumber: String? // Optional field
    var stripeCustomerId: String
    var role: UserRole
    var address: Address? // Added address field (users need to provide this)
}

enum UserRole: String, Codable {
    case admin
    case clientAdult
    case clientChild
}
